const businessData = [
  {
    id: 1,
    name: "FitZone Fitness",
    category: "Gym & Fitness",
    location: "Varanasi, UP",
    address: "123, Sigra Main Road, Varanasi, Uttar Pradesh - 221010",
    phone: "+919876543210",
    whatsapp: "919876543210",
    email: "contact@fitzonefitness.com",
    rating: 4.8,
    reviewCount: 326,
    verified: true,
    isNew: true,
    hours: "Mon – Sun: 5:00 AM – 11:00 PM",
    description:
      "Modern fitness center with professional trainers, advanced equipment and complete workout facilities.",
    longDescription:
      "FitZone Fitness is a full-service gym built for people who take their training seriously, whether that's a first-time gym-goer or a competitive lifter. The floor is split into dedicated zones for cardio, free weights, functional training and recovery, so equipment never feels crowded. Every member gets an onboarding session with a certified trainer to set up a program suited to their goals, and trainers stay on the floor throughout the day for form checks and quick guidance. Lockers, showers and a small proshop round out the facility, and the space is cleaned on a fixed hourly schedule.",
    highlights: [
      "Modern Equipment",
      "Professional Staff",
      "Flexible Timings",
      "Clean Environment",
    ],
    features: [
      "Cardio Zone",
      "Strength Training",
      "CrossFit Area",
      "Personal Training",
      "Steam & Locker Room",
      "Nutrition Guidance",
    ],
    services: [
      {
        name: "Basic Membership",
        description: "Full gym floor access during regular hours.",
        price: "₹1,999",
        unit: "/ month",
      },
      {
        name: "Standard Membership",
        description: "Gym access plus two group classes a week.",
        price: "₹4,999",
        unit: "/ 3 months",
      },
      {
        name: "Premium Membership",
        description: "Unlimited classes, locker and guest passes included.",
        price: "₹8,999",
        unit: "/ 6 months",
      },
      {
        name: "Personal Training",
        description: "One-on-one session with a certified trainer.",
        price: "₹1,500",
        unit: "/ session",
      },
      {
        name: "Diet Plan",
        description: "Custom nutrition plan reviewed monthly.",
        price: "₹2,000",
        unit: "/ month",
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: 2,
    name: "Spice Route",
    category: "Restaurant",
    location: "Varanasi, UP",
    address: "45, Lahurabir Crossing, Varanasi, Uttar Pradesh - 221002",
    phone: "+919876543211",
    whatsapp: "919876543211",
    email: "reservations@spiceroute.in",
    rating: 4.7,
    reviewCount: 518,
    verified: true,
    isNew: false,
    hours: "Mon – Sun: 11:00 AM – 11:00 PM",
    description:
      "Authentic Indian and multi-cuisine dishes served in a cozy and elegant ambience.",
    longDescription:
      "Spice Route brings together regional Indian recipes and a handful of popular multi-cuisine favourites in a warm, low-lit dining room designed for both quick lunches and slower evening meals. The kitchen sources vegetables daily from local markets and grinds its own spice blends, which keeps the menu consistent even as it rotates seasonal specials. There's a private dining alcove for small celebrations, and the team is used to handling birthdays and family get-togethers with advance notice.",
    highlights: [
      "Multi-Cuisine Menu",
      "Family Friendly",
      "Private Dining",
      "Fresh Ingredients",
    ],
    features: [
      "Air-Conditioned Seating",
      "Outdoor Terrace",
      "Live Counter",
      "Party Bookings",
      "Home Delivery",
      "Custom Catering",
    ],
    services: [
      {
        name: "À la carte Dining",
        description: "Full menu access for walk-in guests.",
        price: "₹600",
        unit: "avg / person",
      },
      {
        name: "Buffet Lunch",
        description: "Unlimited North & South Indian spread.",
        price: "₹399",
        unit: "/ person",
      },
      {
        name: "Private Dining Alcove",
        description: "Reserved 8-seat alcove for celebrations.",
        price: "₹2,500",
        unit: "/ booking",
      },
      {
        name: "Home Delivery",
        description: "Delivered within 5 km, packaging included.",
        price: "Free",
        unit: "above ₹499",
      },
      {
        name: "Catering",
        description: "Off-site catering for events, min. 30 guests.",
        price: "₹450",
        unit: "/ plate",
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: 3,
    name: "Glow & Grace Salon",
    category: "Salon",
    location: "Prayagraj, UP",
    address: "22, Civil Lines, Prayagraj, Uttar Pradesh - 211001",
    phone: "+919876543212",
    whatsapp: "919876543212",
    email: "book@glowandgrace.in",
    rating: 4.6,
    reviewCount: 214,
    verified: true,
    isNew: true,
    hours: "Tue – Sun: 10:00 AM – 8:00 PM",
    description:
      "Full-service hair and beauty salon offering expert styling, coloring and grooming.",
    longDescription:
      "Glow & Grace is a unisex salon staffed by stylists trained in current cutting and colour techniques, with a separate quiet room for skin and bridal services. Products used across hair and skin treatments are from established professional brands, and the team is happy to do a short consultation before any chemical service so there are no surprises on the day. The salon takes appointments online or by phone and keeps walk-in slots open during weekday afternoons.",
    highlights: [
      "Expert Stylists",
      "Premium Products",
      "Hygienic Setup",
      "Bridal Packages",
    ],
    features: [
      "Hair Styling & Cutting",
      "Global Colour",
      "Skin Treatments",
      "Bridal Makeup",
      "Spa Pedicure",
      "Men's Grooming",
    ],
    services: [
      {
        name: "Haircut & Styling",
        description: "Consultation, wash, cut and blow-dry.",
        price: "₹499",
        unit: "onwards",
      },
      {
        name: "Global Hair Colour",
        description: "Full colour with ammonia-free products.",
        price: "₹2,999",
        unit: "onwards",
      },
      {
        name: "Bridal Package",
        description: "Trial + wedding day hair and makeup.",
        price: "₹15,999",
        unit: "/ package",
      },
      {
        name: "Spa Pedicure",
        description: "45-minute foot spa and polish.",
        price: "₹899",
        unit: "/ session",
      },
      {
        name: "Men's Grooming",
        description: "Haircut, beard shape and facial.",
        price: "₹699",
        unit: "/ session",
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1519415510236-718bdfcd89c1?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: 4,
    name: "Serenity Spa & Wellness",
    category: "Spa",
    location: "Lucknow, UP",
    address: "7, Hazratganj, Lucknow, Uttar Pradesh - 226001",
    phone: "+919876543213",
    whatsapp: "919876543213",
    email: "hello@serenityspa.in",
    rating: 4.9,
    reviewCount: 189,
    verified: true,
    isNew: false,
    hours: "Mon – Sun: 9:00 AM – 9:00 PM",
    description:
      "Rejuvenating spa treatments and therapies designed to relax the mind and body.",
    longDescription:
      "Serenity Spa & Wellness offers massage, body and skin therapies in individual treatment rooms designed to keep things quiet and unhurried. Therapists are trained in Swedish, deep-tissue and Ayurvedic techniques, and every session opens with a short check-in so pressure and focus areas are set correctly. The centre also runs half-day wellness packages that combine a treatment with steam, sauna and a light herbal refreshment.",
    highlights: [
      "Certified Therapists",
      "Hygienic Rooms",
      "Ayurvedic Therapies",
      "Relaxing Ambience",
    ],
    features: [
      "Swedish Massage",
      "Deep Tissue Therapy",
      "Ayurvedic Treatments",
      "Steam & Sauna",
      "Couple Rooms",
      "Skin Facials",
    ],
    services: [
      {
        name: "Swedish Massage",
        description: "60-minute full body relaxation massage.",
        price: "₹1,799",
        unit: "/ session",
      },
      {
        name: "Deep Tissue Massage",
        description: "75-minute therapy for muscle tension.",
        price: "₹2,199",
        unit: "/ session",
      },
      {
        name: "Ayurvedic Therapy",
        description: "Traditional herbal oil massage.",
        price: "₹2,499",
        unit: "/ session",
      },
      {
        name: "Wellness Half-Day Package",
        description: "Massage + steam, sauna and refreshments.",
        price: "₹3,999",
        unit: "/ package",
      },
      {
        name: "Skin Facial",
        description: "Deep-cleansing facial for all skin types.",
        price: "₹1,499",
        unit: "/ session",
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1620733723572-11c53f73a416?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: 5,
    name: "The Daily Grind Cafe",
    category: "Cafe",
    location: "Varanasi, UP",
    address: "9, Assi Ghat Road, Varanasi, Uttar Pradesh - 221005",
    phone: "+919876543214",
    whatsapp: "919876543214",
    email: "hello@dailygrindcafe.in",
    rating: 4.5,
    reviewCount: 402,
    verified: false,
    isNew: true,
    hours: "Mon – Sun: 8:00 AM – 10:00 PM",
    description:
      "Cozy neighborhood cafe known for its freshly brewed coffee and homemade pastries.",
    longDescription:
      "The Daily Grind is a small-batch coffee cafe that roasts in-house and bakes its pastries fresh every morning. Seating is split between a quiet indoor reading corner and an open patio that's popular for laptop work in the mornings and casual catch-ups in the evening. The menu stays short on purpose — a tight list of coffee, a few breakfast plates and daily pastries — so everything on it is made well.",
    highlights: [
      "Freshly Roasted Coffee",
      "Homemade Pastries",
      "Cozy Seating",
      "Free Wi-Fi",
    ],
    features: [
      "In-House Roastery",
      "Outdoor Patio",
      "Breakfast Menu",
      "Reading Corner",
      "Laptop Friendly",
      "Takeaway Counter",
    ],
    services: [
      {
        name: "Specialty Coffee",
        description: "Pour-over, espresso and cold brew options.",
        price: "₹150",
        unit: "onwards",
      },
      {
        name: "Breakfast Plate",
        description: "Eggs, toast and a side of the day.",
        price: "₹280",
        unit: "onwards",
      },
      {
        name: "Pastry & Bakes",
        description: "Baked fresh every morning, limited stock.",
        price: "₹120",
        unit: "onwards",
      },
      {
        name: "Table Reservation",
        description: "Reserve the patio for small groups.",
        price: "Free",
        unit: "with order",
      },
      {
        name: "Bulk Order / Catering",
        description: "Coffee and snacks for small events.",
        price: "₹100",
        unit: "/ head",
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: 6,
    name: "Framewise Photography Studio",
    category: "Photography Studio",
    location: "Kanpur, UP",
    address: "18, Mall Road, Kanpur, Uttar Pradesh - 208001",
    phone: "+919876543215",
    whatsapp: "919876543215",
    email: "studio@framewise.in",
    rating: 4.8,
    reviewCount: 156,
    verified: true,
    isNew: false,
    hours: "Mon – Sat: 10:00 AM – 7:00 PM",
    description:
      "Professional photography studio specializing in portraits, events and product shoots.",
    longDescription:
      "Framewise runs a fully equipped indoor studio alongside an on-location team for weddings, events and product photography. The in-house set-up covers portrait lighting, a cyclorama wall for product and catalogue shoots, and a small editing suite where clients can review and select shots the same day. Packages are scoped up front so there are no surprise add-ons — travel, editing hours and prints are all quoted before the shoot.",
    highlights: [
      "Professional Equipment",
      "Experienced Team",
      "Same-Day Previews",
      "Custom Packages",
    ],
    features: [
      "Portrait Studio",
      "Product Photography",
      "Event Coverage",
      "Drone Shoots",
      "Photo Editing",
      "Album Design",
    ],
    services: [
      {
        name: "Portrait Session",
        description: "1-hour studio session, 10 edited photos.",
        price: "₹2,999",
        unit: "/ session",
      },
      {
        name: "Product Photography",
        description: "Catalogue shoot, up to 20 products.",
        price: "₹5,999",
        unit: "/ package",
      },
      {
        name: "Event Coverage",
        description: "Half-day coverage with one photographer.",
        price: "₹12,999",
        unit: "/ event",
      },
      {
        name: "Wedding Package",
        description: "Full-day coverage with edited album.",
        price: "₹45,999",
        unit: "/ package",
      },
      {
        name: "Photo Editing (add-on)",
        description: "Advanced retouching per image.",
        price: "₹150",
        unit: "/ photo",
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1471341971476-ae15ff5dd4ea?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1500051638674-ff996a0ec29e?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: 7,
    name: "Urban Nest Interiors",
    category: "Interior Design",
    location: "Prayagraj, UP",
    address: "31, Tagore Town, Prayagraj, Uttar Pradesh - 211002",
    phone: "+919876543216",
    whatsapp: "919876543216",
    email: "studio@urbannest.in",
    rating: 4.7,
    reviewCount: 98,
    verified: true,
    isNew: true,
    hours: "Mon – Sat: 10:00 AM – 6:30 PM",
    description:
      "Creative interior design studio crafting functional and beautiful living spaces.",
    longDescription:
      "Urban Nest Interiors designs homes and small commercial spaces from layout through to furnishing, working with a fixed set of trusted contractors so timelines stay predictable. The studio starts every project with a site visit and a mood-board conversation before any drawings are made, which keeps the final design grounded in how the space will actually be used. Turnaround on a full home design typically runs 3 to 5 weeks depending on scope.",
    highlights: [
      "Custom Designs",
      "End-to-End Execution",
      "Transparent Pricing",
      "On-Time Delivery",
    ],
    features: [
      "Space Planning",
      "Modular Kitchens",
      "Furniture Design",
      "Lighting Design",
      "3D Visualization",
      "Vendor Coordination",
    ],
    services: [
      {
        name: "Design Consultation",
        description: "Site visit and initial concept discussion.",
        price: "₹1,500",
        unit: "/ visit",
      },
      {
        name: "1BHK Full Design",
        description: "Complete design and execution for 1BHK.",
        price: "₹1,80,000",
        unit: "onwards",
      },
      {
        name: "Modular Kitchen",
        description: "Design and fabrication, standard fittings.",
        price: "₹90,000",
        unit: "onwards",
      },
      {
        name: "3D Visualization",
        description: "Photo-realistic renders per room.",
        price: "₹3,500",
        unit: "/ room",
      },
      {
        name: "Furniture Design",
        description: "Custom furniture, design and build.",
        price: "₹8,000",
        unit: "onwards / piece",
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: 8,
    name: "BrightPath Coaching Academy",
    category: "Coaching / Education",
    location: "Varanasi, UP",
    address: "56, Lanka Road, Varanasi, Uttar Pradesh - 221005",
    phone: "+919876543217",
    whatsapp: "919876543217",
    email: "admissions@brightpath.in",
    rating: 4.9,
    reviewCount: 275,
    verified: true,
    isNew: false,
    hours: "Mon – Sat: 7:00 AM – 8:00 PM",
    description:
      "Result-oriented coaching institute offering personalized mentorship for competitive exams.",
    longDescription:
      "BrightPath runs small-batch coaching for school and competitive exams, capping class sizes so every student gets regular one-on-one attention from faculty. Each batch follows a fixed syllabus schedule with weekly tests and a mentor who tracks individual progress and flags weak areas early. Doubt-clearing sessions run daily after regular class hours, and study material is provided as part of every course.",
    highlights: [
      "Small Batch Sizes",
      "Experienced Faculty",
      "Regular Mock Tests",
      "Doubt Clearing Sessions",
    ],
    features: [
      "Foundation Batches",
      "Competitive Exam Prep",
      "Doubt Clearing Desk",
      "Weekly Test Series",
      "Study Material Included",
      "Progress Tracking",
    ],
    services: [
      {
        name: "Foundation Batch",
        description: "Classes 9–10, core subjects.",
        price: "₹3,500",
        unit: "/ month",
      },
      {
        name: "Competitive Exam Batch",
        description: "Classes 11–12 with exam-focused prep.",
        price: "₹6,000",
        unit: "/ month",
      },
      {
        name: "Crash Course",
        description: "6-week intensive revision course.",
        price: "₹9,999",
        unit: "/ course",
      },
      {
        name: "One-on-One Mentoring",
        description: "Personal doubt-clearing and planning.",
        price: "₹800",
        unit: "/ session",
      },
      {
        name: "Test Series",
        description: "Full mock test series with analysis.",
        price: "₹2,000",
        unit: "/ series",
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: 9,
    name: "AutoCare Motors",
    category: "Automobile / Car Service",
    location: "Lucknow, UP",
    address: "14, Kanpur Road, Lucknow, Uttar Pradesh - 226012",
    phone: "+919876543218",
    whatsapp: "919876543218",
    email: "service@autocaremotors.in",
    rating: 4.6,
    reviewCount: 341,
    verified: true,
    isNew: false,
    hours: "Mon – Sat: 9:00 AM – 7:00 PM",
    description:
      "Reliable car servicing and repair center with certified technicians and genuine parts.",
    longDescription:
      "AutoCare Motors handles routine servicing, diagnostics and repair work for most car brands using genuine and OEM-equivalent parts. Every job comes with a written estimate before work begins and a digital inspection report showing what was checked and replaced. The workshop also offers pick-up and drop within the city, which is useful for anyone dropping a car off on a workday.",
    highlights: [
      "Certified Technicians",
      "Genuine Parts",
      "Free Pick & Drop",
      "Transparent Billing",
    ],
    features: [
      "Periodic Servicing",
      "Engine Diagnostics",
      "AC & Electrical Repair",
      "Denting & Painting",
      "Tyre & Wheel Care",
      "Insurance Claims",
    ],
    services: [
      {
        name: "General Service",
        description: "Oil change, filters and safety check.",
        price: "₹2,499",
        unit: "onwards",
      },
      {
        name: "AC Service",
        description: "Gas top-up and cooling system check.",
        price: "₹1,499",
        unit: "onwards",
      },
      {
        name: "Denting & Painting",
        description: "Per panel, colour-matched paint.",
        price: "₹3,500",
        unit: "/ panel",
      },
      {
        name: "Wheel Alignment & Balancing",
        description: "All four wheels, computerized.",
        price: "₹899",
        unit: "/ visit",
      },
      {
        name: "Pick-up & Drop",
        description: "Within city limits, free with service.",
        price: "Free",
        unit: "with booking",
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1625047509168-a7026f36de04?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: 10,
    name: "PixelPulse Digital Marketing",
    category: "Digital Marketing",
    location: "Prayagraj, UP",
    address: "5, Civil Lines, Prayagraj, Uttar Pradesh - 211001",
    phone: "+919876543219",
    whatsapp: "919876543219",
    email: "hello@pixelpulse.in",
    rating: 4.7,
    reviewCount: 132,
    verified: true,
    isNew: true,
    hours: "Mon – Sat: 10:00 AM – 7:00 PM",
    description:
      "Full-service digital marketing agency helping local businesses grow their online presence.",
    longDescription:
      "PixelPulse works with local and regional businesses on the marketing they actually need — a working website, a Google Business profile that ranks, and social media that's posted on a schedule instead of in bursts. Every engagement starts with a short audit of the client's current online presence, followed by a plan with clear monthly deliverables rather than vague retainers. Reporting is sent monthly in plain language, not raw analytics dumps.",
    highlights: [
      "Local SEO Focus",
      "Clear Monthly Reporting",
      "Dedicated Account Manager",
      "No Long Lock-Ins",
    ],
    features: [
      "Google Business Optimization",
      "Social Media Management",
      "Website Design",
      "Paid Ad Campaigns",
      "SEO & Content",
      "Monthly Reporting",
    ],
    services: [
      {
        name: "Local SEO Package",
        description: "Google Business + local search optimization.",
        price: "₹6,999",
        unit: "/ month",
      },
      {
        name: "Social Media Management",
        description: "12 posts/month across 2 platforms.",
        price: "₹8,999",
        unit: "/ month",
      },
      {
        name: "Website Design",
        description: "5-page responsive business website.",
        price: "₹19,999",
        unit: "one-time",
      },
      {
        name: "Paid Ad Campaign",
        description: "Google/Meta ad setup and management.",
        price: "₹5,000",
        unit: "/ month + ad spend",
      },
      {
        name: "Monthly Reporting Add-on",
        description: "Detailed plain-language performance report.",
        price: "Included",
        unit: "with any plan",
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1533750349088-cd871a92f312?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1611926653458-09294b3142bf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
    ],
  },
];

export const getBusinessById = (id) =>
  businessData.find((business) => business.id === Number(id));

export default businessData;