const listingData = [
  {
    id: 1,
    name: "FitZone Fitness",
    category: "Gym & Fitness",
    location: "Varanasi, UP",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
    rating: 4.8,
    reviewCount: 326,
    verified: true,
    description:
      "Modern fitness center with professional trainers, advanced equipment and complete workout facilities.",
    isNew: true,
  },
  {
    id: 2,
    name: "Spice Route",
    category: "Restaurant",
    location: "Varanasi, UP",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    rating: 4.7,
    reviewCount: 518,
    verified: true,
    description:
      "Authentic Indian and multi-cuisine dishes served in a cozy and elegant ambience.",
    isNew: false,
  },
  {
    id: 3,
    name: "Glow & Grace Salon",
    category: "Salon",
    location: "Prayagraj, UP",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80",
    rating: 4.6,
    reviewCount: 214,
    verified: true,
    description:
      "Full-service hair and beauty salon offering expert styling, coloring and grooming.",
    isNew: true,
  },
  {
    id: 4,
    name: "Serenity Spa & Wellness",
    category: "Spa",
    location: "Lucknow, UP",
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80",
    rating: 4.9,
    reviewCount: 189,
    verified: true,
    description:
      "Rejuvenating spa treatments and therapies designed to relax the mind and body.",
    isNew: false,
  },
  {
    id: 5,
    name: "The Daily Grind Cafe",
    category: "Cafe",
    location: "Varanasi, UP",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
    rating: 4.5,
    reviewCount: 402,
    verified: false,
    description:
      "Cozy neighborhood cafe known for its freshly brewed coffee and homemade pastries.",
    isNew: true,
  },
  {
    id: 6,
    name: "Framewise Photography Studio",
    category: "Photography Studio",
    location: "Kanpur, UP",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80",
    rating: 4.8,
    reviewCount: 156,
    verified: true,
    description:
      "Professional photography studio specializing in portraits, events and product shoots.",
    isNew: false,
  },
  {
    id: 7,
    name: "Urban Nest Interiors",
    category: "Interior Design",
    location: "Prayagraj, UP",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    rating: 4.7,
    reviewCount: 98,
    verified: true,
    description:
      "Creative interior design studio crafting functional and beautiful living spaces.",
    isNew: true,
  },
  {
    id: 8,
    name: "BrightPath Coaching Academy",
    category: "Coaching / Education",
    location: "Varanasi, UP",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=80",
    rating: 4.9,
    reviewCount: 275,
    verified: true,
    description:
      "Result-oriented coaching institute offering personalized mentorship for competitive exams.",
    isNew: false,
  },
  {
    id: 9,
    name: "AutoCare Motors",
    category: "Automobile / Car Service",
    location: "Lucknow, UP",
    image: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800&q=80",
    rating: 4.6,
    reviewCount: 341,
    verified: true,
    description:
      "Reliable car servicing and repair center with certified technicians and genuine parts.",
    isNew: false,
  },
  {
    id: 10,
    name: "PixelPulse Digital Marketing",
    category: "Digital Marketing",
    location: "Prayagraj, UP",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    rating: 4.7,
    reviewCount: 132,
    verified: true,
    description:
      "Full-service digital marketing agency helping local businesses grow their online presence.",
    isNew: true,
  },
];

export default listingData;