const listingData = [
  {
    id: 1,
    name: "FitZone Fitness",
    category: "Gym & Fitness",
    location: "Varanasi, UP",
    address: "123, Sigra Main Road, Varanasi, Uttar Pradesh - 221010",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
    rating: 4.8,
    reviewCount: 326,
    verified: true,
    description:
      "Modern fitness center with professional trainers, advanced equipment and complete workout facilities.",
    isNew: true,
  },
  {
    id: 2,
    name: "Spice Route",
    category: "Restaurant",
    location: "Varanasi, UP",
    address: "45, Lahurabir Crossing, Varanasi, Uttar Pradesh - 221002",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    rating: 4.7,
    reviewCount: 518,
    verified: true,
    description:
      "Authentic Indian and multi-cuisine dishes served in a cozy and elegant ambience.",
    isNew: false,
  },
  {
    id: 3,
    name: "Glow & Grace Salon",
    category: "Salon",
    location: "Prayagraj, UP",
    address: "22, Civil Lines, Prayagraj, Uttar Pradesh - 211001",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80",
    rating: 4.6,
    reviewCount: 214,
    verified: true,
    description:
      "Full-service hair and beauty salon offering expert styling, coloring and grooming.",
    isNew: true,
  },
    {
    id: 4,
    name: "GlowSkin Beauty Clinic",
    category: "Skin Care Clinic",
    location: "Lucknow, UP",
    address: "7, Hazratganj, Lucknow, Uttar Pradesh - 226001",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    rating: 4.9,
    reviewCount: 189,
    verified: true,
    description:
      "Advanced skin care clinic offering dermatologist-led treatments for healthy, glowing skin.",
    isNew: false,
  },
  {
    id: 5,
    name: "The Daily Grind Cafe",
    category: "Cafe",
    location: "Varanasi, UP",
    address: "9, Assi Ghat Road, Varanasi, Uttar Pradesh - 221005",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
    rating: 4.5,
    reviewCount: 402,
    verified: false,
    description:
      "Cozy neighborhood cafe known for its freshly brewed coffee and homemade pastries.",
    isNew: true,
  },
  {
    id: 6,
    name: "Framewise Photography Studio",
    category: "Photography Studio",
    location: "Kanpur, UP",
    address: "18, Mall Road, Kanpur, Uttar Pradesh - 208001",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80",
    rating: 4.8,
    reviewCount: 156,
    verified: true,
    description:
      "Professional photography studio specializing in portraits, events and product shoots.",
    isNew: false,
  },
  {
    id: 7,
    name: "Urban Nest Interiors",
    category: "Interior Design",
    location: "Prayagraj, UP",
    address: "31, Tagore Town, Prayagraj, Uttar Pradesh - 211002",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    rating: 4.7,
    reviewCount: 98,
    verified: true,
    description:
      "Creative interior design studio crafting functional and beautiful living spaces.",
    isNew: true,
  },
  {
    id: 8,
    name: "BrightPath Coaching Academy",
    category: "Coaching / Education",
    location: "Varanasi, UP",
    address: "56, Lanka Road, Varanasi, Uttar Pradesh - 221005",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=80",
    rating: 4.9,
    reviewCount: 275,
    verified: true,
    description:
      "Result-oriented coaching institute offering personalized mentorship for competitive exams.",
    isNew: false,
  },
  {
    id: 9,
    name: "AutoCare Motors",
    category: "Automobile / Car Service",
    location: "Lucknow, UP",
    address: "14, Kanpur Road, Lucknow, Uttar Pradesh - 226012",
    image: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800&q=80",
    rating: 4.6,
    reviewCount: 341,
    verified: true,
    description:
      "Reliable car servicing and repair center with certified technicians and genuine parts.",
    isNew: false,
  },
  {
    id: 10,
    name: "PixelPulse Digital Marketing",
    category: "Digital Marketing",
    location: "Prayagraj, UP",
    address: "5, Civil Lines, Prayagraj, Uttar Pradesh - 211001",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    rating: 4.7,
    reviewCount: 132,
    verified: true,
    description:
      "Full-service digital marketing agency helping local businesses grow their online presence.",
    isNew: true,
  },
  {
    id: 11,
    name: "PowerHouse Gym",
    category: "Gym & Fitness",
    location: "Varanasi, UP",
    address: "18, Mahmoorganj Main Road, Varanasi, Uttar Pradesh - 221010",
    image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&q=80",
    rating: 4.5,
    reviewCount: 189,
    verified: true,
    description:
      "Well-equipped gym in Mahmoorganj offering strength training, cardio and group fitness classes.",
    isNew: true,
  },
  {
    id: 12,
    name: "Iron Pulse Fitness Studio",
    category: "Gym & Fitness",
    location: "Varanasi, UP",
    address: "62, Bhelupur Road, Varanasi, Uttar Pradesh - 221010",
    image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&q=80",
    rating: 4.6,
    reviewCount: 143,
    verified: false,
    description:
      "Compact fitness studio in Bhelupur known for personal training and functional workout programs.",
    isNew: true,
  },
  {
    id: 13,
    name: "NextGen Career Coaching",
    category: "Coaching / Education",
    location: "Varanasi, UP",
    address: "29, Sigra Main Road, Varanasi, Uttar Pradesh - 221010",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80",
    rating: 4.8,
    reviewCount: 201,
    verified: true,
    description:
      "Coaching institute focused on career guidance, competitive exams and skill-based mentorship.",
    isNew: false,
  },
  {
    id: 14,
    name: "Royal Bites Restaurant",
    category: "Restaurant",
    location: "Lucknow, UP",
    address: "33, Hazratganj Main Road, Lucknow, Uttar Pradesh - 226001",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    rating: 4.6,
    reviewCount: 287,
    verified: true,
    description:
      "Popular multi-cuisine restaurant known for its royal Awadhi flavours and warm hospitality.",
    isNew: true,
  },
  {
    id: 15,
    name: "Serenity Spa & Salon",
    category: "Salon",
    location: "Kanpur, UP",
    address: "11, Mall Road, Kanpur, Uttar Pradesh - 208001",
    image: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=800&q=80",
    rating: 4.7,
    reviewCount: 176,
    verified: true,
    description:
      "Relaxing salon and spa offering hair styling, skin treatments and rejuvenating therapies.",
    isNew: false,
  },
];

export default listingData;